source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!


target 'Bricks_Example', :exclusive => true do
  pod "Bricks", :path => "../"
end

target 'Bricks_Tests', :exclusive => true do
  pod "Bricks", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
